Finloans/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using FinLibrary.Model.Services;
using FinLibrary.Repo.EF;
using NLog;
using Paystack.Net.SDK.Transactions;

namespace Finloans.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILoanService _db;
        private readonly Logger _logger = LogManager.GetCurrentClassLogger();

        public HomeController(ILoanService db)
        {
            _db = db;
        }

        [HttpGet]
        public ActionResult Index()
        {



            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(LoanInfo item, string LoanType)
        {
            //LoanInfo item


            try
            {
               

                if (!ModelState.IsValid)
                {

                    return View();
                }
                item.LoanType = LoanType;

                _logger.Info(item.LoanType);
                _db.Add(item);

                Session["item"] = item;
                
            }
            catch (Exception e)
            {
                //Logger logger = LogManager.GetLogger("fileLogger");

                // add custom message and pass in the exception
                _logger.Error(e, "Whoops!");
            }
            return RedirectToAction("FilteredResult", "Loan");

        }

        public ActionResult AllLoans()
        {
            var model = _db.GetAll();
            return View(model);
        }


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        [HttpGet]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";


            return View();
        }

        


        [HttpGet]
        public ActionResult SingleBlog()
        {
            return View();
        }

      
    }
}

Finloans/Controllers/SubController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Paystack.Net.SDK.Transactions;

namespace Finloans.Controllers
{
    public class SubController : Controller
    {
        // GET: Sub
        public async Task<ActionResult> Index(int value)
        {

            int numb = 0;
            int month = 0;

            switch (value)
            {
                case 1:
                    numb = 500000;
                    month = 1;

                    break;
                case 2:
                    numb = 2200000;
                    month = 6;
                    break;
                case 3:
                    numb = 4000000;
                    month = 12;
                    break;
                default:
                    numb = 0;
                    break;
            }

            TempData["month"] = month;
            string secretKey = ConfigurationManager.AppSettings["PayStackSec"];
            var paystackTransactionAPI = new PaystackTransaction(secretKey);
            string email = User.Identity.GetUserName();
            var response = await paystackTransactionAPI.InitializeTransaction(email, numb, callbackUrl: "https://localhost:44377/Suscription/VerifyPayment");
            if (response.status)
            {
                Session["paymentRef"] = response.data.reference;
                Response.AddHeader("Access-Control-Allow-Origin", "*");
                Response.AppendHeader("Access-Control-Allow-Origin", "*");
                return Redirect(response.data.authorization_url);
            }

            return RedirectToAction("Failed");


        }

        [Authorize]
        public async Task<ActionResult> VerifyPayment()
        {
            string reference = (string)Session["paymentRef"];
            string secretKey = ConfigurationManager.AppSettings["PayStackSec"];
            var paystackTransactionApi = new PaystackTransaction(secretKey);
            var response = await paystackTransactionApi.VerifyTransaction(reference);

            if (response.status && response.data.status.Equals("success"))
            {
                //string userId = User.Identity.GetUserId();
                //var loggedInUser = _repo.GetUserById(userId);
                //loggedInUser.ActiveSub = true;
                //Index
                var month = Convert.ToInt32(TempData["month"]);
                var startDate = DateTime.Now;
                var endDate = DateTime.Now.AddDays(month * 31);




                //UserIdentity.userEmail = User.Identity.GetUserName();
                //UserIdentity.ValidityPeriod = endDate - startDate;



                //_repo.Save();
                //int providerId = (int)Session["providerId"];
                // Session["paymentRef"] = null;
                //return RedirectToAction("Details", "Provider", new { id = providerId });
            }
            return RedirectToAction("Failed");
        }
    }
}

Finloans/Views/Home/AllLoans.cshtml
@model IEnumerable<FinLibrary.Repo.EF.LoanInfo>

@{
    ViewBag.Title = "AllLoans";
}

<h2>AllLoans</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LoanType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AmountWithInterest)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LoanType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Duration)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AmountWithInterest)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Finloans/Views/Home/Contact.cshtml
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_3">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Contact us</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->
    <!-- ================ contact section start ================= -->
    <section class="contact-section section_padding">
        <div class="container">
            <div class="d-none d-sm-block mb-5 pb-4">
                <div id="map" style="height: 480px;"></div>
                <script>
          function initMap() {
            var uluru = {lat: 6.524379, lng: 3.379206};
            var grayStyles = [
              {
                featureType: "all",
                stylers: [
                  { saturation: -90 },
                  { lightness: 50 }
                ]
              },
              {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
            ];
            var map = new google.maps.Map(document.getElementById('map'), {
              center: {lat: 6.441664, lng: 3.535591},
              zoom: 9,
              styles: grayStyles,
              scrollwheel:  false
            });
          }

                </script>
                <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>

            </div>


            <div class="row">
                <div class="col-12">
                    <h2 class="contact-title">Get in Touch</h2>
                </div>
                <div class="col-lg-8">
                    <form class="form-contact contact_form" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate">
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">

                                    <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'" placeholder='Enter Message'></textarea>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <input class="form-control" name="name" id="name" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'" placeholder='Enter your name'>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <input class="form-control" name="email" id="email" type="email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" placeholder='Enter email address'>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <input class="form-control" name="subject" id="subject" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Subject'" placeholder='Enter Subject'>
                                </div>
                            </div>
                        </div>
                        <div class="form-group mt-3">
                            <button type="submit" class="button button-contactForm btn_4 boxed-btn">Send Message</button>
                        </div>
                    </form>
                </div>
                <div class="col-lg-4">
                    <div class="media contact-info">
                        <span class="contact-info__icon"><i class="ti-home"></i></span>
                        <div class="media-body">
                            <h3>Buttonwood, California.</h3>
                            <p>Rosemead, CA 91770</p>
                        </div>
                    </div>
                    <div class="media contact-info">
                        <span class="contact-info__icon"><i class="ti-tablet"></i></span>
                        <div class="media-body">
                            <h3>00 (440) 9865 562</h3>
                            <p>Mon to Fri 9am to 6pm</p>
                        </div>
                    </div>
                    <div class="media contact-info">
                        <span class="contact-info__icon"><i class="ti-email"></i></span>
                        <div class="media-body">
                            <h3>support@colorlib.com</h3>
                            <p>Send us your query anytime!</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ================ contact section end ================= -->

Finloans/Views/Home/Index.cshtml
@*@{*@
@*ViewBag.Title = "Home Page";
    }

    <div class="jumbotron">
        <h1>ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>*@







@*var option = new List<SelectListItem>
    {

            new SelectListItem {Text = "Student", Value = "1"},
                new SelectListItem {Text = "Mortgages", Value = "2"},
                new SelectListItem {Text = "Personal", Value = "3"},
                new SelectListItem {Text = "Auto", Value = "4"},
                new SelectListItem {Text = "Small_Business", Value = "5"}

            };



    }


    @model  FinLibrary.Repo.EF.LoanInfo


    @{
        ViewBag.Title = "Home Page";
    }


    <div class="jumbotron jumbotron-fluid">
        <h1>LOAN-COMPARER</h1>
        <h2 class="lead">MAKING MONEY ACCESSIBLE TO ALL </h2>
        <p>Get access to the loan you need at the lowest rate possible</p>
    </div>




    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Loan Information</h4>
            <p>Please enter the loan information below</p>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LoanType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">*@
@*@Html.EnumDropDownListFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })*@
@*@Html.DropDownList("LoanType", option, new { @class = "form-control-lg" })
                    @Html.ValidationMessageFor(model => model.LoanType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

    <div>*@
@*@Html.ActionLink("Back to List", "Index")*@
@*</div>*@

@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@


@using System.Web.UI.WebControls
@model  FinLibrary.Repo.EF.LoanInfo


<!-- header-end -->
<!-- slider_area_start -->
<div class="slider_area">
    <div class="single_slider  d-flex align-items-center slider_bg_1">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-7 col-md-6">
                    <div class="slider_text">
                        <h3 class="wow fadeInRight" data-wow-duration="1s" data-wow-delay=".1s">Get Loan for your Business growth or startup</h3>
                        <div class="sldier_btn wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".2s">
                            @*<a href="#" class="boxed-btn3">How it Works</a>*@
                            @Html.ActionLink("Subscribe", "Sub", "",new { @class ="boxed-btn3" })
                        </div>
                    </div>
                </div>




             

                    <div class="col-lg-5 col-md-6">
                        <div class="payment_form white-bg wow fadeInDown" data-wow-duration="1.2s" data-wow-delay=".2s">
                            <div class="info text-center">
                                <h4>How much do you want?</h4>
                                <p>We provide online instant cash loans with quick</p>
                            </div>
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form">
                                    <div class="row">

                                        <div class="col-lg-12">
                                            <div class="single_input">
                                                <select class="wide" name="LoanType">
                                                    <option data-display="LoanType">LoanType</option>
                                                    <option value="1">Student</option>
                                                    <option value="2">Mortgages</option>
                                                    <option value="3">Personal</option>
                                                    <option value="4">Auto</option>
                                                    <option value="5">Small Business</option>

                                                </select>
                                                @Html.ValidationMessageFor(model => model.LoanType, "", new {@class = "text-danger"})
                                            </div>
                                        </div>

                                        <div class="col-lg-12">
                                            <div class="single_input">
                                                @Html.EditorFor(model => model.Duration, new {htmlAttributes = new {@class = "form-control", @placeholder="Duration"}})
                                                @Html.ValidationMessageFor(model => model.Duration, "", new {@class = "text-danger"})
                                            </div>
                                        </div>


                                        <div class="col-lg-12">
                                            <div class="single_input">
                                                @Html.EditorFor(model => model.Amount, new {htmlAttributes = new {@class = "form-control", PlaceHolder="Amount"}})
                                                @Html.ValidationMessageFor(model => model.Amount, "", new {@class = "text-danger"})
                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <p>You have to pay: <span>$0</span></p>
                                <div class="submit_btn">
                                    <button class="boxed-btn3" type="submit">Continue</button>
                                </div>
                            }
                            </div>
            </div>
                



                @*<div class="col-lg-5 col-md-6">
            <div class="payment_form white-bg wow fadeInDown" data-wow-duration="1.2s" data-wow-delay=".2s">
                <div class="info text-center">
                    <h4>How much do you want?</h4>
                    <p>We provide online instant cash loans with quick</p>
                </div>


                <div class="form">
                    @Html.AntiForgeryToken()
                    <div class="row">

                        <div class="col-lg-12">
                            <div class="single_input">
                                <select class="wide" name="Amount">
                                    <option data-display="Amount">Amount</option>
                                    <option value="1">Student</option>
                                    <option value="2">Mortgages</option>
                                    <option value="3">Personal</option>
                                    <option value="4">Auto</option>
                                    <option value="5">Small Business</option>

                                </select>
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="single_input">
                                <input type="text" placeholder="Duration" name="Duration" />
                            </div>
                        </div>


                        <div class="col-lg-12">
                            <div class="single_input">
                                <input type="text" placeholder="Amount" name="Amount" />
                            </div>
                        </div>

                    </div>
                </div>
                <p>You have to pay: <span>$0</span></p>
                <div class="submit_btn">
                    <button class="boxed-btn3" type="submit">Continue</button>
                </div>
            </div>
        </div>*@





            </div>
        </div>
    </div>
</div>
<!-- slider_area_end -->
<!-- footer start -->