Finloans/Controllers/LoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using FinLibrary.Model.Services;
using FinLibrary.Repo.EF;
using Paystack.Net.SDK.Transactions;

namespace Finloans.Controllers
{
    public class LoanController : Controller
    {
        private readonly ICompanyService _db;
        private readonly ISubService sub;

        public LoanController(ICompanyService db, ISubService sub)
        {
            this._db = db;
            this.sub = sub;
        }
        //GET: Loan
       [HttpGet]
        public ActionResult Index()
        {
            var model = _db.GetAll();
            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CompanyInfo item)
        {

            if (ModelState.IsValid)
            {
                _db.Add(item);
                return RedirectToAction("Index");
            }

            return View();

        }

        [HttpGet]
        [Authorize]
        public ActionResult Details(int id)
        {
            var item = (LoanInfo)Session["item"];
            var email = (string)Session["Email"];
            var breakdown = _db.LoanBreakDown(item.Amount, item.Duration, id, email);
            var model = _db.Get(id);
            ViewBag.breakdown = breakdown;
            ViewBag.time = (int)item.Duration;
            ViewBag.amount = (int)item.Amount;
            ViewBag.res = model.WebAddress;





            return View(model);
        }


        [HttpGet]
        public ActionResult FilteredResult()
        {
            var item = (LoanInfo)Session["item"];
            var model = _db.GetAllFiltered(item);

            return View(model);
        }



        [HttpGet]
        public ActionResult GetAllCompaines()
        {

            var model = _db.GetAll();
            return View(model);
        }

        [HttpGet]
        public ActionResult Website(int id)
        {
            var model = _db.Get(id);
            var email = (string)Session["Email"];

            _db.Unique(id, email);

            return Redirect($"https://{model.WebAddress}");
        }

        [HttpGet]
        public ActionResult Subscribe()
        {
            var model = _db.Get(1);

            return View(model);

        }

        [HttpGet]
        public async Task<ActionResult> Payment(int id)
        {

         var  numb = _db.Amount(id);
            //ViewBag.Message = "Your contact page.";

            var email = (string)Session["Email"];
            var paystackTransactionAPI = new PaystackTransaction("sk_test_4f260b0736ab1d07afe4642756c7868359abb180");
            //var response = await paystackTransactionAPI.InitializeTransaction("davidcloudobi@gmail.com", 500000);
            var response = await paystackTransactionAPI.InitializeTransaction(email, numb, callbackUrl: "https://localhost:44367/");
            if (response.status)
            {
             

                Response.AddHeader("Access-Control-Allow-Origin", "*");
                Response.AppendHeader("Access-Control-Allow-Origin", "*");

                var currentSub = sub.Get(email);
                if (currentSub == null)
                {
                    sub.AddSub(id, email);
                }

                if (currentSub != null)
                {
                    sub.UpdateSub(id, email);
                }

                Response.Redirect(response.data.authorization_url);

            }
            else
            {
                return RedirectToAction("Error");
            }




          

            return RedirectToAction("Error");

           
        }


        [HttpGet]

        public  ActionResult Error()
        {

            return View();
        }
    }
}

Finloans/Views/Shared/_Layout.cshtml
@*<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
    </html>*@



<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Finloans</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="~/Content/site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/img/favicon.png">
    <!-- Place favicon.ico in the root directory -->
    <!-- CSS here -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/css/magnific-popup.css">
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/css/themify-icons.css">
    <link rel="stylesheet" href="~/Content/css/nice-select.css">
    <link rel="stylesheet" href="~/Content/css/flaticon.css">
    <link rel="stylesheet" href="~/Content/css/gijgo.css">
    <link rel="stylesheet" href="~/Content/css/animate.css">
    <link rel="stylesheet" href="~/Content/css/slicknav.css">
    <link rel="stylesheet" href="~/Content/css/style.css">
    <!-- <link rel="stylesheet" href="~/Content/css/responsive.css"> -->
</head>

<body>
    <!--[if lte IE 9]>
             <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="~/Content/https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
         <![endif]-->
    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="~/Content/index.html">
                                        <img src="~/Content/img/logo.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                            <li>@Html.ActionLink("Subscribe", "Subscribe", "Loan")</li>
                                            <li>@Html.ActionLink("About", "About", "Home")</li>
                                            @*<li>
            <a href="~/Content/#">pages <i class="ti-angle-down"></i></a>
            <ul class="submenu">
                <li><a href="~/Content/apply.html">apply loan</a></li>
                <li><a href="~/Content/elements.html">elements</a></li>
            </ul>
        </li>*@
                                            @*<li>
            <a href="~/Content/#">blog <i class="ti-angle-down"></i></a>
            <ul class="submenu">
                <li><a href="~/Content/blog.html">blog</a></li>
                <li><a href="~/Content/single-blog.html">single-blog</a></li>
            </ul>
        </li>*@
                                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                            <li>@Html.ActionLink("Blog", "SingleBlog", "Home")</li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            @Html.Partial("_LoginPartial")
                            @*<div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                    <div class="Appointment">
                                        <div class="phone_num d-none d-xl-block">
                                            <a href="~/Content/#"> <i class="fa fa-phone"></i> +10 673 567 367</a>
                                        </div>
                                        <div class="d-none d-lg-block">
                                            <a class="boxed-btn4" href="~/Content/apply.html">Apply for a Loan</a>
                                        </div>
                                    </div>
                                </div>*@
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>



    @RenderBody()

    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-4 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="~/Content/img/footer_logo.png" alt="">
                                </a>
                            </div>
                            <p>
                                finloan@support.com <br>
                                +10 873 672 6782 <br>
                                600/D, Green road, NewYork
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                Services
                            </h3>
                            <ul>
                                <li><a href="#">SEO/SEM </a></li>
                                <li><a href="#">Web design </a></li>
                                <li><a href="#">Ecommerce</a></li>
                                <li><a href="#">Digital marketing</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                            <h3 class="footer_title">
                                Useful Links
                            </h3>
                            <ul>
                                <li><a href="#">About</a></li>
                                <li><a href="#">Blog</a></li>
                                <li><a href="#"> Contact</a></li>
                                <li><a href="#">Support</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                            <h3 class="footer_title">
                                Subscribe
                            </h3>
                            <form action="#" class="newsletter_form">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Subscribe</button>
                            </form>
                            <p class="newsletter_text">
                                Esteem spirit temper too say adieus who direct esteem esteems
                                luckily.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->
    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="~/Content/js/vendor/modernizr-3.5.0.min.js"></script>
    <script src="~/Content/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/Content/js/popper.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <script src="~/Content/js/isotope.pkgd.min.js"></script>
    <script src="~/Content/js/ajax-form.js"></script>
    <script src="~/Content/js/waypoints.min.js"></script>
    <script src="~/Content/js/jquery.counterup.min.js"></script>
    <script src="~/Content/js/imagesloaded.pkgd.min.js"></script>
    <script src="~/Content/js/scrollIt.js"></script>
    <script src="~/Content/js/jquery.scrollUp.min.js"></script>
    <script src="~/Content/js/wow.min.js"></script>
    <script src="~/Content/js/nice-select.min.js"></script>
    <script src="~/Content/js/jquery.slicknav.min.js"></script>
    <script src="~/Content/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Content/js/plugins.js"></script>
    <script src="~/Content/js/gijgo.min.js"></script>
    <script src="~/Content/js/slick.min.js"></script>



    <!--contact js-->
    <script src="~/Content/js/contact.js"></script>
    <script src="~/Content/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/Content/js/jquery.form.js"></script>
<script src="~/Content/js/jquery.validate.min.js"></script>
<script src="~/Content/js/mail-script.js"></script>


<script src="~/Content/js/main.js"></script>


@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>

</html>